#ifndef NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H
#define NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H

// ================================
#define DEBUG_SOMETHING 0
#define DEBUG_SOMETHING2 0
#define CHECK_COUT_CHMAP 1
#define CHECK_COUT_DETCONF 1
#define CHECK_COUT_CONDITIONALRUN 0
#define CHECK_COUT_LFTDC 0
#define DEBUG_LFTDC 0
#define CHECK_COUT_DRIFTTIME 0

#define FILEOUT_LFTDC 0
#define FILEOUT_DRIFTTIME 0

#define CHECK_COUT_MAKEPAIRPLANEHITCLUSTER 0

#define CHECK_COUT_PARSEMESSAGES 0
#define CHECK_COUT_DETCONF_REGISTERING 0

#define CHECK_COUT_UTOF_TIMING 1
#define DEBUG_KLDC_TRACK_SEARCH 0
#define CHECK_COUT_ELAPSED_TIME 0
#define FILEOUT_ELAPSED_TIME 0
#define FILEOUT_ELAPSED_TIME_TREE 0
#define FILEOUT_THROUGHPUT 1 // Sliceごとではなく、ContitionalRun()ごと
#define CHECK_COUT_GLOBALZ 0
// ================================


#endif  // NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H