#ifndef NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H
#define NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H

// ================================
#define DEBUG_SOMETHING 0
#define DEBUG_SOMETHING2 0
#define CHECK_COUT_CHMAP 1
#define CHECK_COUT_DETCONF 1
#define CHECK_COUT_CONDITIONALRUN 0
#define CHECK_COUT_LFTDC 0
#define CHECK_COUT_PARSEMESSAGES 0
#define CHECK_COUT_DETCONF_REGISTERING 0

#define CHECK_COUT_UTOF_TIMING 1
// ================================


#endif  // NESTDAQ_TIMEFRAMESLICERBYTRACKDEBUGGER_H